import { Interests } from '@/domain/enums/interests'

export enum InterestsGroup {
  Care = 'Care',
  Food = 'Food',
  Sports = 'Sports',
  Travelling = 'Travelling',
  WaterSnowSports = 'WaterSnowSports',
  Wellness = 'Wellness',
  Leisure = 'Leisure',
  Hobby = 'Hobby',
  Music = 'Music',
  Games = 'Games',
  Digital = 'Digital',
  Arts = 'Arts',
}

export const groupedInterests: Record<InterestsGroup, Interests[]> = {
  Care: [
    Interests.SelfCare,
    Interests.Meditation,
    Interests.Makeup,
    Interests.SkinCare,
    Interests.Vegan,
  ],
  Food: [
    Interests.Sushi,
    Interests.Coffee,
    Interests.Food,
    Interests.IceCream,
    Interests.BubbleTea,
    Interests.BBQ,
    Interests.CraftBeer,
    Interests.ColdTea,
    Interests.Tea,
    Interests.Wine,
    Interests.Ramen,
  ],
  Sports: [
    Interests.Triathlon,
    Interests.Basketball,
    Interests.MartialArts,
    Interests.Gym,
    Interests.Cricket,
    Interests.Volleyball,
    Interests.Sports,
    Interests.Baseball,
    Interests.Football,
    Interests.Bowing,
    Interests.Skates,
    Interests.Cheerleading,
    Interests.Bambindon,
    Interests.Bowling,
    Interests.Fencing,
    Interests.Soccer,
    Interests.RollerSkating,
    Interests.Boxing,
  ],
  WaterSnowSports: [
    Interests.Hockey,
    Interests.Diving,
    Interests.Skiing,
    Interests.Snowboarding,
    Interests.SupSurfing,
    Interests.Surfing,
    Interests.Swimming,
  ],
  Wellness: [
    Interests.HomeWorkout,
    Interests.OutdoorWorkouts,
    Interests.Talkiiing,
    Interests.Pilates,
    Interests.Activism,
    Interests.Yoga,
    Interests.ActiveLifestyle,
  ],
  Arts: [
    Interests.Ballet,
    Interests.ACapella,
    Interests.GalleryOfArts,
    Interests.Songwriting,
    Interests.Drawing,
    Interests.Arts,
    Interests.Museums,
    Interests.Tattoos,
  ],
  Leisure: [
    Interests.Startups,
    Interests.Entrepreneurship,
    Interests.Parties,
    Interests.Marvel,
    Interests.Movies,
    Interests.Feminism,
    Interests.Shopping,
    Interests.Clothes,
    Interests.Investment,
    Interests.AlcoholicTrip,
    Interests.Clubs,
    Interests.Broadway,
    Interests.Series,
    Interests.Fashion,
    Interests.Astrology,
    Interests.MBTI,
    Interests.Picnic,
    Interests.Comedy,
    Interests.RealEstate,
    Interests.Manga,
    Interests.Rave,
    Interests.BBC,
    Interests.Politics,
  ],
  Hobby: [
    Interests.Bakery,
    Interests.Calligraphy,
    Interests.Aquarium,
    Interests.Travel,
    Interests.Languages,
    Interests.SocialNetworks,
    Interests.Photography,
    Interests.Reading,
    Interests.Poetry,
    Interests.StandUp,
    Interests.Fishing,
    Interests.Content,
    Interests.Quests,
    Interests.Camping,
    Interests.Blogging,
    Interests.Collecting,
    Interests.Cooking,
    Interests.DIY,
    Interests.Quiz,
    Interests.Skateboard,
    Interests.Volunteering,
    Interests.Automobiles,
  ],
  Music: [
    Interests.ElectronicMusic,
    Interests.Karaoke,
    Interests.CountryMusic,
    Interests.KPop,
    Interests.Concerts,
    Interests.RussianRap,
    Interests.RussianRock,
    Interests.Music,
    Interests.Drums,
    Interests.Vocals,
    Interests.Choir,
  ],
  Games: [
    Interests.TableGames,
    Interests.TableTennis,
    Interests.DungeonsAndDragons,
    Interests.Dota2,
    Interests.Fortnite,
    Interests.Pubg,
    Interests.Cybersports,
  ],
  Travelling: [
    Interests.Jogging,
    Interests.Running,
    Interests.Hiking,
    Interests.Mountains,
    Interests.RockClimbing,
    Interests.Motorsports,
    Interests.AutoRacing,
    Interests.BikeRacing,
  ],
  Digital: [
    Interests.Instagram,
    Interests.NFT,
    Interests.Memes,
    Interests.Anime,
    Interests.TikTok,
    Interests.Twitch,
    Interests.Netflix,
    Interests.Disney,
    Interests.Podcasts,
    Interests.Cryptocurrency,
    Interests.Linux,
  ],
}
